### PR TITLE
rename .css.scss to .scss and update references

### PR DESCRIPTION
**Pull request by afomi**
this bash script was handy:

```
for file in *.css.scss
do
  mv "$file" "`basename $file | cut -d. -f1`.scss"
done
```

### CODE REVIEW

**Comment by afomi** [comment]
related to: https://www.pivotaltracker.com/story/show/85577518

**Comment by mikem** [comment]
Looks good. :+1:

**Comment by afomi** [comment]
After reviewing the other open PR's, only `ember-cli` contains a couple .scss files, so I'll merge this.  I'll sync with @tonywok about the renaming of .css.scss files to .scss

**Comment by tonywok** [comment]
@ryanwold Should get picked up by your upstream changes when merging
master. Thanks :)

**Pull request merged**
