### PR TITLE
Update rails g task generator for ember-cli

### PR DESCRIPTION
**Pull request by neo-tahi**
an updated version of https://github.com/Tahi-project/tahi/pull/818. 

Tested this and it works, following https://github.com/Tahi-project/tahi/wiki/HOWTO:-Install-a-Custom-Card

### CODE REVIEW

**Comment by mikem** [comment]
:+1: looks OK to me.

**Comment by afomi** [comment]
one remaining issue we just found: the task card template is posting to its own route. For example, `SampleCard` posts to `sample_card_tasks` route when clicking the 'Completed' button.  Looking at this before merging.  This also raises the issue of specs (or testing framework) for Custom Cards.

**Comment by rizwanreza** [comment]
I am also not sure about having the card's JavaScript be in a separate directory. Is there a way the card's code (both Rails and Ember) can be contained in a single directory?

**Comment by afomi** [comment]
@rizwanreza, good call. I chatted about this with @egh this morning as well.  I don't think we have to solve for this immediately, but it will need to be addressed soon.  Let's chat!

**Comment by afomi** [comment]
merging this branch with the understanding we'll need to revisit how to package the Rails Engine and Ember-CLI Addon generated by `rails g task custom_tahi_card`

**Pull request merged**
