### PR TITLE
[#85817976] Can now open the assign reviewers task

### PR DESCRIPTION
**Pull request by neo-tahi**
We are now able to open the popup.

There are other things broken, which we've made another bug card for and are working on.

— AJP DT

### CODE REVIEW

**Comment by mikem** [comment]
Can we add a test for this, please?

**Comment by neo-tahi** [comment]
@mikem test added, but the build failed...

**Comment by mikem** [comment]
Let's merge this fix since it's a blocker, and work on the spec in another PR.

A feature test is not appropriate for this code change, it should be in the component test instead.

**Comment by DTrejo** [comment]
(This only goes wrong for this one type of card, this is why we put the
test here.)

**Comment by andibyday** [comment]
Merging this :)

**Pull request merged**
