### PR TITLE
APERTA-13013 Add hierarchical improvements and minor touchups

### PR DESCRIPTION
**Pull request by noxmwalsh**
JIRA issue: https://jira.plos.org/jira/browse/APERTA-13013

#### What this PR does:

This PR provides hierarchical improvements to certain cards (for example, if there's a display-children element with children, they are indented now) and minor enhancements to provide additional clarity.

#### Special instructions for Review or PO:

I highly recommend you get a diverse set of papers to look at in various states (which does exist to an extend with existing seeds). Even better, if there is a dump from a real-life production use-case, that would be even better.

After a dump is retrieved, run the following Rake task for a semi-random sampling of papers in different publishing states:

bundle exec rake export:random_manuscript_zips
For just a single specific paper, just pass in doi into this Rake task:

bundle exec rake export:manuscript_zip[pbio.2000123] 
Both commands should generate zip files in the export directory. Unzip it and you should be able to see a series of .csv, .html, and other assets in the directory.

#### Notes

I had to abandon using proper list elements due to various ways that children parts of having a lot of edge cases.  The option I went with seems the most consistent along all the cards.

#### Major UI changes

N/A, although the look of the generated cards themeselves is different.

#### Code Review Tasks:

**Author tasks** (delete tasks that don't apply to your PR, this list should be finished before code review):

- [ ] If I made any UI changes at all, I've let the entire QA team know in the JIRA ticket and in the Aperta QA hipchat room.
- [ ] I have set the correct component(s) in the JIRA ticket
- [ ] I have set an appropriate resolution in the JIRA ticket
- [ ] If I changed the database schema, I enforced database constraints.
- [ ] If I created a migration, I updated the base data.yml seeds file. [instructions](https://developer.plos.org/confluence/display/TAHI/Seeds+maintenance)
- [ ] If I modified `app/services/journal_factory.rb`, I updated the base data.yml seeds file. [instructions](https://developer.plos.org/confluence/display/TAHI/Seeds+maintenance)
- [ ] I have ensured that the Heroku Review App has successfully deployed and is ready for PO UAT.
- [ ] I added an entry to `## [Unreleased]` in CHANGELOG.md

If I modified any environment variables:
- [ ] I made a pull request to change the files on the [molten repo](https://github.com/PLOS/molten/tree/dev/pillar/aperta) {PR LINK}
- [ ] I double-checked the `app.json` file to make sure that the heroku review apps are still inheriting the correct environment variables from staging

If I need to migrate existing data:
- [ ] If a data-migration rake task is needed, the task is found in `lib/tasks/data_migrations` within the `data:migrate` namespace. Example task name: `aperta_9999_migration_description`
- [ ] If there are steps to take outside of `rake db:migrate` for Heroku or other environments, I added copy-pastable instructions to [the confluence release page](https://developer.plos.org/confluence/display/TAHI/Deployment+information+for+Release)
- [ ] I verified the data-migration's results with `rake db:test_migrations` (complicated migrations should also have real specs)
- [ ] I've talked through the ramifications of the data-migration with Product Owners in regards to deployment timing
- [ ] If I created a data migration, I added pre- and post-migration assertions.

**Reviewer tasks** (these should be checked or somehow noted before passing on to PO):
- [ ] I read through the JIRA ticket's AC before doing the rest of the review
- [ ] I ran the code (in the review environment or locally). I agree the running code fulfills the Acceptance Criteria as stated on the JIRA ticket
- [ ] I read the code; it looks good
- [ ] I have found the tests to be sufficient for both positive and negative test cases

### CODE REVIEW

**Comment by egh** [comment]
@noxmwalsh Is this ready for review?

**Comment by noxmwalsh** [comment]
@egh Sorry, this needs one more thing fixed.  I've been stuck on other tasks, but I intend to wrap this up today.

**Comment by noxmwalsh** [comment]
I've surpassed the timebox nature of this ticket and didn't have time to come back to this, so I'm just planning on spawning a new ticket for the HTML enhancement.  This ticket just covers the hierarchical aspects by having related items as part of a question or group be indented.

**Review by egh — APPROVED** [review]
LGTM

**Pull request merged**
