### PR TITLE
Feature/docker

### PR DESCRIPTION
**Pull request by egh**
Support running Tahi dependencies in docker containers. The containers are:
- postgres
- redis
- solr
- event server
- ihat
- ihat worker
- postgres (for ihat)
- redis (for ihat)

Includes a detailed README-fig.md for getting started, which also includes detailed information on getting S3 setup. Test by me on ubuntu 14.10 and @martinhaye on Mac.

### CODE REVIEW

**Comment by afomi** [comment]
Thanks @egh! Busy week here, focusing on other things. I'll sync with the team on Monday to ensure this gets reviewed.

**Comment by egh** [comment]
Thanks, @afomi !

**Comment by mikem** [comment]
Let's reopen this if interest sparks up again.

**Comment by egh** [comment]
Works for me. Thanks.

**Pull request closed without merging**
