### PR TITLE
Ember CLI

### PR DESCRIPTION
**Pull request by pairing**

### CODE REVIEW

**Comment by rizwanreza** [comment]
:star: :star: :star: 

Good stuff!

**Comment by tonywok** [comment]
@oliver---- Once this is merged there's a few things up next: merge some (existing) bug fixes from pivotal, and then take a peek that that work you guys have been doing. :+1:

**Comment by oliver----** [comment]
@tonywok sounds good. Ping me when you want to start then I give you a tour.

**Comment by oliver----** [comment]
@tonywok Tried the current version, and it works :+1:
While you are doing the merge I start with reworking our stuff.

**Pull request merged**
