### PR TITLE
Distinguish between Rails and RSpec helper

### PR DESCRIPTION
**Pull request by rizwanreza**
New versions of RSpec generate `rails_helper` and `spec_helper`. You can use `spec_helper` for code that doesn't depend on Rails. It leads to faster TDD feedback loop, and thus more productive sessions.

### CODE REVIEW

**Comment by neo-tahi** [comment]
:ship: it!
— @DTrejo

**Comment by annapetry** [comment]
:rocket: looks stellar.

**Comment by neo-tahi** [comment]
:rocket: :ship: :it:

**Comment by neo-tahi** [comment]
This broke the master build:

<https://semaphoreapp.com/tahi-project/tahi/branches/master/builds/285>

image

**Pull request merged**
