### PR TITLE
Format date helper

### PR DESCRIPTION
**Pull request by theharq**
Use moment js to easily format dates, by default will use the "LL" format if is not specified

```{{format-date invitation.createdAt}}```
March 9, 2015

```{{format-date invitation.createdAt format="L"}}```
03/09/2015

### CODE REVIEW

**Comment by theharq** [comment]
I wanna mention that this handlebars helper was created with the ember generator.. I had trouble making the actual syntax to work with the tests

To test this handlebars snippets I could create an object view and compile it, because the helper expects 2 parameters, the value and options but I decided to keep it simple and send the second parameter as an object, this issue https://github.com/rwjblue/ember-qunit/issues/5  mentions the addition of moduleForSnippet we could wait for it and keep the bound helpers simple

**Comment by mikem** [comment]
@theharq any chance you could find a place in our code where we format a date and use this helper, so we have a use case in core?

**Comment by theharq** [comment]
hi @mikem, well after looking the code I did not find a place where you guys are formatting a date at least in the ember templates, the reason I created this helper is because I thought that could be useful to have a consistency in the format we display dates ( a human readable or international format, sometimes I have a hard time when I see american date format hehe ), but I think, maybe we could move the calculation to the client side (is a good practice) for example here:
https://github.com/Tahi-project/tahi/blob/master/app/serializers/activity_feed_serializer.rb#L18

We gain some flexibility of momentjs also, I could update the default format of the helper to use the one use in the serializer:
```
created_at.strftime('%B %e, %Y %l:%M %p')
```
is equivalent in moment to:
```
moment().format('LLL');  // March 10, 2015 9:44 AM
```

let me know what do you think, if its too specific to be in the tahi core I could leave it in "my" engine ;)

**Comment by mikem** [comment]
@theharq there's a date on the profile. Visit `https://localhost:5000/profile` and add an affiliation. You can format those dates using moment.js.

**Comment by theharq** [comment]
A.T. Still University of Health Sciences
2015-02-01 - 2015-02-28
test@example.com

**Comment by theharq** [comment]
yup it will work, ex:
now we have 
```<div>{{a.startDate}} - {{a.displayEndDate}}</div>```
and renders
A.T. Still University of Health Sciences
2015-02-01 - 2015-02-28
test@example.com

but if change the dates to and leave the default format ( I can use any format that momentjs support)

```<div>{{format-date a.startDate}} - {{format-date a.displayEndDate}}</div>````

I get

A.T. Still University of Health Sciences
February 1, 2015 - February 28, 2015
test@example.com

which I consider more human friendly, so the answer is yes, we could use this helper in parts of the tahi core

**Comment by mikem** [comment]
@theharq great! Please update this PR to use `format-date` on the profile page.

**Comment by theharq** [comment]
I've updated the helper to ignore invalid formats, because the returns in the profile is sometimes "Current" so the helper just ignore this invalid strings to parse

let me know any other improvement ;)

**Pull request merged**
