### PR TITLE
APERTA-8396 Disable prepared statements for now to see if it addresse…

### PR DESCRIPTION
**Pull request by tadp**
JIRA issue: https://developer.plos.org/jira/browse/APERTA-8396

#### What this PR does:

This disables prepared statements to see if this will allow postgres to use less memory when storing gigantic queries. 

This change only changes it locally.  The key part of the change is here:

https://github.com/PLOS/molten/pull/305

---

#### Code Review Tasks:

Author tasks:

- [ ] If I created a migration, I updated the base data.yml seeds file. [instructions](https://developer.plos.org/confluence/display/TAHI/Seeds+maintenance)

If I modified any environment variables:
- [ ] I made a pull request to change the files on the [molten repo](https://github.com/PLOS/molten/tree/dev/pillar/aperta) {PR LINK}
- [ ] I double-checked the `app.json` file to make sure that the heroku review apps are still inheriting the correct environment variables from staging

- [ ] If I made any UI changes, I've let QA know.

If I need to migrate production data:

- [ ] If a data-migration rake task is needed, the task is found in `lib/tasks/data-migrations` within the `data:migrate` namespace. Example task name: `aperta_9999_migration_description`
- [ ] If there are steps to take outside of `rake db:migrate` for Heroku or other environments, I added copy-pastable instructions to [the confluence release page](https://developer.plos.org/confluence/display/TAHI/Deployment+information+for+Release)
- [ ] I verified the data-migration's results on a copy of production data
- [ ] I've talked through the ramifications of the data-migration with Product Owners in regards to deployment timing

Reviewer tasks:

- [x] I skimmed the code; it makes sense
- [x] I read the code; it looks good
- [x] I ran the code (in the review environment or locally)
- [x] I performed a 5 minute walkthrough of the site looking for oddities
- [ ] I have found the tests to be sufficient
- [x] I agree the code fulfills the Acceptance Criteria
- [x] I agree the author has fulfilled their tasks

#### After the Code Review:

Author tasks:

- [ ] The Product Team has reviewed and approved this feature

…s our memory issue

### CODE REVIEW

**Comment by we4tech** [comment]
Hi @tadp it's been a while. I would like to know your experience about running without prepared statements. How is it now? Did you find any possible issues? 

In one of our applications, we have seen it has an adverse effect if you have complex queries it contributes more CPU usages as PG has to parse and plan on the fly.

Look forward to hearing about your experience.

**Comment by egh** [comment]
@we4tech This fix was mostly to reduce memory usage on the postsgresql server, if I recall correctly.

**Comment by tadp** [comment]
@we4tech I'm no longer on this project so I can't speak much on how it is now, I think @egh can talk more about that.

However, it is totally understandable if it results in more CPU usage for complex queries.  It is a bit of a tradeoff.  Is the query relatively simple?  Is it unique? (If it is relatively unique, like in our example of checking permissions, then we found the tradeoff for more memory to be worth it).

It isn't something that would be recommended to turn off throughout an entire app.

**Comment by egh** [comment]
Hi @tadp !!!!! :wave:

**Comment by tadp** [comment]
Hi @egh!

**Pull request merged**
