### PR TITLE
add rake task to completely install a tahi engine

### PR DESCRIPTION
**Pull request by egh**

### CODE REVIEW

**Comment by rizwanreza** [comment]
Looks good at first glance. I'd like to refactor it and test it once we are doing production deploys.

**Comment by egh** [comment]
Thanks! Any chance of merging then? :)

**Comment by neo-tahi** [comment]
Merged. 

– RR

**Comment by egh** [comment]
Thanks! @4thethrillofit suggested that we switch to `npm --save` instead of manually editing the `package.json`. I'll submit a fix soon.

**Pull request merged**
