### PR TITLE
Use jquery ui drag and drop

### PR DESCRIPTION
**Pull request by neo-tahi**
- drag within a column
- drag between columns
- changes are saved
- no flashing / wierdness

— @rizwanreza @DTrejo

### CODE REVIEW

**Comment by mikem** [comment]
Looks OK to me. Merge when green :+1:

**Comment by afomi** [comment]
do we have UI or integration specs covering these behaviors?

references: 
* https://gist.github.com/bbonamin/3129666
* http://heywill.com/blog/2012/12/15/using-capybara-to-drag-a-jquery-ui-sortable-onto-a-jquery-ui-droppable

**Comment by neo-tahi** [comment]
@afomi: We have tried using those before, they do not work in our case.

**Comment by afomi** [comment]
okay. just checkin'. glad drag & drop is better than before :smile_cat:

**Pull request merged**
